### ISSUE TITLE
Cannot import topology

### ISSUE THREAD

**Issue by marti-puig** [williamhunter/ToPy#55]
Hi, I'm a beginner and I'm not too familiar with this kind of issues. I've followed the install instructions and when I run ToPy with one of the example files I keep on getting the following error:
  File "/home/mpuig/topy-0.4.1-py-2/examples/cantilever/optimise.py", line 9, in <module>
    from topy import topology
ImportError: cannot import name 'topology' from 'topy'

Any help would be much appreciated!
Thanks!

**Comment by mohdibntarek** [comment]
Shameless self promotion: try https://github.com/JuliaTopOpt/TopOpt.jl.

**Comment by williamhunter** [comment]
Julia is a great language, I use it a bit for work. I saw your talk on a JuliaConf, I think?

It seems I really need to upgrade this to work with Python 3. Just amazed that people still want to use it (15 years after I wrote it). I actually had a look at https://pypi.org/project/scikit-sparse/ yesterday to see if I can make Topy work with CHOLMOD (instead of PySparse). I'll see, just need to finish off some "real work" side-hustles first.

**Comment by williamhunter** [comment]
> Hi, I'm a beginner and I'm not too familiar with this kind of issues. I've followed the install instructions and when I run ToPy with one of the example files I keep on getting the following error: File "/home/mpuig/topy-0.4.1-py-2/examples/cantilever/optimise.py", line 9, in from topy import topology ImportError: cannot import name 'topology' from 'topy'
> 
> Any help would be much appreciated! Thanks!

Apologies for the delayed response, but I'm just not getting time to look into this (I have a 'real' job, and when I have free time I prefer to do other things).

**Comment by marti-puig** [comment]
> 



> > Hi, I'm a beginner and I'm not too familiar with this kind of issues. I've followed the install instructions and when I run ToPy with one of the example files I keep on getting the following error: File "/home/mpuig/topy-0.4.1-py-2/examples/cantilever/optimise.py", line 9, in from topy import topology ImportError: cannot import name 'topology' from 'topy'
> > Any help would be much appreciated! Thanks!
> 
> Apologies for the delayed response, but I'm just not getting time to look into this (I have a 'real' job, and when I have free time I prefer to do other things).

Hi! Don't worry, I managed to get it to work today, I was just making a silly mistake when importing Pysparse.
Thanks for your answer though!

**Comment by williamhunter** [comment]
Can you elaborate? Because other people may make the same 'silly' mistake and it will help them if they know what to do or not to do.

Also, are you getting Topy to work with Python 3 or 2?

**Comment by marti-puig** [comment]
> Can you elaborate? Because other people may make the same 'silly' mistake and it will help them if they know what to do or not to do.
> 
> Also, are you getting Topy to work with Python 3 or 2?

I'm working with Python 2.7 as suggested in the Wiki. I had this error happening because I hadn't installed Pysparse properly. Turns out I needed Numpy 1.15 for Pysparse to work with Python 2.7, and the correct version of Numpy needs to be installed **before** Pysparse is installed.

**Comment by williamhunter** [comment]
Ah, OK, thanks. But it is working now? You're getting results?

**Comment by marti-puig** [comment]
> Ah, OK, thanks. But it is working now? You're getting results?

Yes, I've gotten the examples to work fine.

**Comment by williamhunter** [comment]
Great, enjoy it. It's quite fun to work with.

**Comment by mohdibntarek** [comment]
>Julia is a great language, I use it a bit for work. I saw your talk on a JuliaConf, I think?

Nice! What do you do for work these days? Here is the video, clickbait title but good content https://www.youtube.com/watch?v=sBqdkxPXluU.
